
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGNACION CADENA CONST IDENTIFICADOR LET NUMERO VAR\n    declaracion : VAR IDENTIFICADOR ASIGNACION expresion\n                | LET IDENTIFICADOR ASIGNACION expresion\n                | CONST IDENTIFICADOR ASIGNACION expresion\n    \n    expresion : NUMERO\n              | CADENA\n    '
    
_lr_action_items = {'VAR':([0,],[2,]),'LET':([0,],[3,]),'CONST':([0,],[4,]),'$end':([1,11,12,13,14,15,],[0,-1,-4,-5,-2,-3,]),'IDENTIFICADOR':([2,3,4,],[5,6,7,]),'ASIGNACION':([5,6,7,],[8,9,10,]),'NUMERO':([8,9,10,],[12,12,12,]),'CADENA':([8,9,10,],[13,13,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaracion':([0,],[1,]),'expresion':([8,9,10,],[11,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaracion","S'",1,None,None,None),
  ('declaracion -> VAR IDENTIFICADOR ASIGNACION expresion','declaracion',4,'p_declaracion','interfaz.py',50),
  ('declaracion -> LET IDENTIFICADOR ASIGNACION expresion','declaracion',4,'p_declaracion','interfaz.py',51),
  ('declaracion -> CONST IDENTIFICADOR ASIGNACION expresion','declaracion',4,'p_declaracion','interfaz.py',52),
  ('expresion -> NUMERO','expresion',1,'p_expresion','interfaz.py',67),
  ('expresion -> CADENA','expresion',1,'p_expresion','interfaz.py',68),
]
